export const OPERATE_SOLUTION_INFO = 'OPERATE_SOLUTION_INFO'
export const OPERATE_SOLUTION_NAME_EDIT = 'OPERATE_SOLUTION_NAME_EDIT'
export const OPERATE_SOLUTION_LAYER_ADD = 'OPERATE_SOLUTION_LAYER_ADD'
export const OPERATE_SOLUTION_LAYER_DEL = 'OPERATE_SOLUTION_LAYER_DEL'
export const OPERATE_SOLUTION_LAYER_SELECTED = 'OPERATE_SOLUTION_LAYER_SELECTED'
export const OPERATE_SOLUTION_ALLLAYER_SELECTED = 'OPERATE_SOLUTION_ALLLAYER_SELECTED'
export const OPERATE_SOLUTION_LAYER_EDIT = 'OPERATE_SOLUTION_LAYER_EDIT'
export const OPERATE_SOLUTION_LAYERNAME_EDIT = 'OPERATE_SOLUTION_LAYERNAME_EDIT'
export const OPERATE_SOLUTION_LAYERZINDEX_EDIT = 'OPERATE_SOLUTION_LAYERZINDEX_EDIT'
export const OPERATE_SOLUTION_LAYER_VISIBLE = 'OPERATE_SOLUTION_LAYER_VISIBLE'
export const OPERATE_SOLUTION_LAYER_DUPLICATE = 'OPERATE_SOLUTION_LAYER_DUPLICATE'

export const OPERATE_SOLUTION_LAYER_LAYOUT_MODIFY = 'OPERATE_SOLUTION_LAYER_LAYOUT_MODIFY'
export const OPERATE_SOLUTION_LAYER_PAINT_MODIFY = 'OPERATE_SOLUTION_LAYER_PAINT_MODIFY'
export const OPERATE_SOLUTION_LAYER_TYPE_MODIFY = 'OPERATE_SOLUTION_LAYER_TYPE_MODIFY'
export const OPERATE_SOLUTION_LAYER_FILTER_MODIFY = 'OPERATE_SOLUTION_LAYER_FILTER_MODIFY'
export const OPERATE_SOLUTION_LAYER_ZOOMRANGE_MODIFY = 'OPERATE_SOLUTION_LAYER_ZOOMRANGE_MODIFY'
export const OPERATE_LAYER_STYLE_INFO = 'OPERATE_LAYER_STYLE_INFO'
export const OPERATE_LAYER_STYLE_UNSELECTED = 'OPERATE_LAYER_STYLE_UNSELECTED'
export const OPERATE_LAYER_SOURCE_ATTR_LIST = 'OPERATE_LAYER_SOURCE_ATTR_LIST'

export const WAREHOUSE_SOURCES = 'WAREHOUSE_SOURCES'
export const WAREHOUSE_SOURCE_LAYERS = 'WAREHOUSE_SOURCE_LAYERS'
export const WAREHOUSE_SOURCES_CONFIRM = 'WAREHOUSE_SOURCES_CONFIRM'
export const WAREHOUSE_SOURCE_LAYER_CHANGE = 'WAREHOUSE_SOURCE_LAYER_CHANGE'

export const DISPLAY_INTERFACE_ROUTE = 'DISPLAY_INTERFACE_ROUTE'

export const MAP_INIT = "MAP_INIT"
export const MAP_LAYER_REORDER = "MAP_LAYER_REORDER"
export const MAP_FLY = "MAP_FLY"
export const MAP_FLY_STEP = "MAP_FLY_STEP"