export const STUDIO_SOLUTION_LIST = 'STUDIO_SOLUTION_LIST' //解决方案列表
export const STUDIO_SOLUTION_ADD = 'STUDIO_SOLUTION_ADD' //解决方案新增
export const STUDIO_SOLUTION_DEL = 'STUDIO_SOLUTION_DEL' //解决方案删除
export const STUDIO_SOLUTION_EDIT = 'STUDIO_SOLUTION_EDIT' //解决方案编辑
export const STUDIO_SOLUTION_MODIFY = 'STUDIO_SOLUTION_MODIFY' //解决方案修改
export const STUDIO_SOLUTION_COPY = 'STUDIO_SOLUTION_COPY' //解决方案复制

export const STUDIO_TEMPLATE_LIST = 'STUDIO_TEMPLATE_LIST'
export const STUDIO_TEMPLATE_SELECT = 'STUDIO_TEMPLATE_SELECT'
export const STUDIO_MENU_LINK = 'STUDIO_MENU_LINK'